### PR TITLE
Ceiros multiplayer

### LINKED ISSUE #139: More Twisted Greatsword and Drill Containment Unit bugs on multiplayer
## Issue Description
	Expected behavior: I expected both items mentioned in the title to function normally
	Actual behavior: Twisted Greatsword's sound plays multiple times when used from the inventory(1), Sentinel Tincture does not rotate with either Ripshatter or Drill Containment unit(2), and the spawn area's cutout disappears rarely(3)
	Context: I was testing things that were broken in the previous demo build

## Reproduction
		Mod list: Boss Cursor, Starlight River, YABHB, and Cheat Sheet
		Config settings: Default
		Game settings: Colour lighting, cursor grid visible, the rest default
		Gameplay events happening: Using the Drill Containment Unit to see if any arena blocks could be mined
		Your inputs: Using Twisted Greatsword from the inventory(1), mounting the Drill Containment Unit with the Sentinel Tincture(2), and I just opened a world(3)
		OS: Windows 10

## Additional context and log files
**I'm not sure how to recreate the third bug listed here, so it might just be a one-time thing. I'm reporting it anyways to be safe.** 
		Here are my logs:
		[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627423/server.log)
		[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627424/client.log)

### PR DESCRIPTION
**Pull request by TripleFate**
### What is being fixed or optimized? Is there an associated issue?
This is to fix the bugs found from testers from the first mp compatibility test run. This should resolve the following issues:

#141 -- fix for glass stamina vessel, fire bug super shake, death cutscene crash, resonant crystal despawn. could not replicate background failing to spawn.
#140 -- jittering seems like it may be impossible to fix while the platforms are NPCs, but the fall through should be fixed
#139 -- fixed the issues mentioned here
#138 -- fixed ghost banners, could not replicate black backgrounds
#134 -- fixed via giving boss invincibility in the leaving phase
#133 -- fixed (was sp only bug somehow)
#122 -- fixed

fixes with no associated issue:
barrier drawing with yoyo out fixed
fixes for tiledummies despawning locally + overhaul of the tiledummy dict system for mp compatibility

### What are the implementation specifics of this change? Are there any consequences?

The premium glass idol holder that is in the demo temple was not in the master branch so it was not fixed in this pr, but its probably just replacing Item.NewItem(Main.LocalPlayer.Center, ItemType<Items.Vitric.GlassIdolPremiumEdition>()); with Main.LocalPlayer.QuickSpawnItem(ItemType<Items.Vitric.GlassIdolPremiumEdition>());

gameplay changes:
firebugs had a lot of jittering on their turns so their velocity handling was changed from assigning directly to a clamped add.

Cieros was given invincibility in the leaving phase

### CODE REVIEW

File: Content/NPCs/BaseTypes/MovingPlatform.cs [hunk 1]
```diff
@@ -34,33 +41,52 @@ public sealed override void SetDefaults()
...
 
-            //    var playerFeet = new Rectangle((int)player.position.X, (int)player.position.Y + (player.height - 2), player.width, 4);
-            //    var platformHitbox = new Rectangle((int)npc.position.X, (int)npc.position.Y, npc.width, 4);
-
-            //    if (playerFeet.Intersects(platformHitbox) && player.position.Y <= npc.position.Y)
-            //        player.position += npc.velocity;
-            //}
+            float yDistTraveled = npc.position.Y - prevPos.Y;
+
+            if (npc.velocity != Vector2.Zero && Math.Abs(npc.velocity.Y) > 1f && (npc.velocity.Y < 0 && yDistTraveled < npc.velocity.Y * 1.5 && yDistTraveled > npc.velocity.Y * 6))
```
Comment (ScalarVector1) [inline Content/NPCs/BaseTypes/MovingPlatform.cs:63]: This check could be simplified

**Review by ScalarVector1 — COMMENTED** [review]
Few minor style and conciseness issues, but otherwise looks great.
